const products = [
    { 
        id: 1,
        name: "Mackbook Pro 13",
        price: "1300",
        rating: 5,
        image: "https://www.notebookcheck.org/fileadmin/Notebooks/News/_nc3/photo_1517336714731_489689fd1ca8_9.jpeg",
        details: "El MacBook Pro de 13 pulgadas incluye el nuevo chip M2, que lo convierte en un titán. Ofrece hasta 20 horas de autonomía1 y un sistema de refrigeración activa para mantener un ritmazo incluso en tareas muy complejas",
        category: "Desktop",
        stock: 5, 
    },
    { 
        id: 2,
        name: "Iphone 13 Pro",
        price: "700",
        rating: 5,
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-13-pro-family-hero?wid=940&hei=1112&fmt=png-alpha&.v=1644969385433",
        details: "El iPhone 13 repite el diseño del iPhone 12, que a su vez era una inspiración del iPhone 5. Como tal, la parte trasera está hecha de cristal y los marcos, totalmente rectos, de aluminio. Personalmente, me gustaba más el diseño de los iPhone 11 en parte por sus marcos redondeados, ya que permiten un mejor agarre",
        category: "Phone",
        stock: 10, 
    },
    { 
        id: 3,
        name: "Ipad Mini 6",
        price: "499",
        rating: 3,
        image: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/refurb-ipad-pro-11-wifi-spacegray-2020?wid=1150&hei=1150&fmt=jpeg&qlt=95&.v=1627667236000",
        details: "El Apple iPad Mini 8.3 2021 WiFi 64GB blanco cuenta con una CPU Hexa-core, una de las más avanzadas en el mercado. El sistema operativo es iPadOS 15, actualizable a iPadOS 15.1. Si eres amante de la fotografía con este iPad podrás disfrutar de ellas en su pantalla de 8.3 pulgadas en alta resolución o realizarlas tu mismo con su cámara",
        category: "Ipad",
        stock: 5, 
    },
    { 
        id: 4,
        name: "Airpods ",
        price: "200",
        rating: 3,
        image: "https://cdn.ipadizate.com/2022/05/AirPods-Pro.1652106350.5463.jpg",
        details: "El audio espacial con seguimiento dinámico de la cabeza convierte la música y las películas (o series) en una experiencia tridimensional. Sentirás que el sonido llega de todas partes a tu alrededor, como si estuvieras en medio de una sala de cine o tocaras en la propia orquesta.",
        category: "Auriculares",
        stock: 5, 
    },
    { 
        id: 5,
        name: "GoPro ",
        price: "319",
        rating: 2,
        image: "https://phantom-marca.unidadeditorial.es/3ff99a90e41847540b09a0c4177c6930/resize/1320/f/jpg/assets/multimedia/imagenes/2021/09/16/16318042170762.jpg",
        details: "Esta es la HERO8, una cámara de acción GoPro versátil e inamovible. Gracias a su diseño optimizado, es más cómoda de llevar que nunca. Además, permite cambiar de soporte en segundos sin necesidad de carcasa. Viene con una funda compacta. ",
        category: "Desktop",
        stock: 5, 
    },
    { 
        id: 6,
        name: "Apple Watch 7",
        price: "900",
        rating: 5,
        image: "https://i.blogs.es/10ff7f/apple-watch-series-7-00-01/1366_2000.jpg",
        details: "El MacBook Pro de 13 pulgadas incluye el nuevo chip M2, que lo convierte en un titán. Ofrece hasta 20 horas de autonomía1 y un sistema de refrigeración activa para mantener un ritmazo incluso en tareas muy complejas",
        category: "Desktop",
        stock: 5, 
    },

];

export default products;